### PR TITLE
Use cl-labels instead of defun-in-defun

### PR DESCRIPTION
**Pull request by syohex**
We should use cl-lables or similar API for defining local functions.

### CODE REVIEW

**Comment by rmuslimov** [comment]
Thanks, @syohex! I didn't know about cl-flet, cl-labels before.

**Comment by rmuslimov** [comment]
I temporary reverted this merge, because I've started to get exception when I'm trying to switch to details page:

```
mapcar: Symbol's function definition is void: convert-item
```

**Comment by syohex** [comment]
Ah, sorry. I suppose I should use `#'convert-item` instead of `'convert-item`

**Comment by syohex** [comment]
Could you try following patch ? I use #'convert-item instead of 'convert-item

https://gist.github.com/syohex/afc8b08f62f0eb28b7c0

**Comment by rmuslimov** [comment]
Thanks, it's worked!

**Pull request merged**
